services:
  db:
    image: surrealdb/surrealdb:latest
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - rocksdb:/data/mydatabase.db
      - --strict
    volumes:
      - ./docker-data/surrealdb:/data
